name: Run Script
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # 👈 这里改成 latest 即可
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python hotrank.py
